### ISSUE TITLE
How is accept-nano affected by the spam attacks?

### ISSUE THREAD

**Issue by MihaiVoinea** [accept-nano/accept-nano#10]
Hello,

I'm looking to use accept-nano in a project, but I was wondering how is it affected by spam attacks?

Is there the possibility that a user loses his NANO or that a transaction goes through without being accepted or anything else like that?

I'm new when it comes to this, so please excuse me if the answers are obvious.

Thank you!

**Comment by BatuAksoy** [comment]
Hey @MihaiVoinea,
First of all let me clarify a few things. Accept-nano is just a gateway over a nano node. You can think it as an observer, it just says to customers  "pay this nano address" and then waits for the transaction to be verified on the nano node.

What is a spam attack? Spam attack is a kind of attack that keeps the ecosystem busy. You can think it as ridiculous amount transactions occur in a second with very tiny amount of nano. And it prevents the actual transactions to be processed. It has several impacts on this ecosystem:
1. If you run your own nano node, your nano node can be lagging behind. So that your node will be aware of a transaction even if it is verified by other nodes on the network. You will need either a faster node or will wait for next updates of nano node. We experienced similar issue at putio and after v21.3 patch lag of our node eliminated.
2. There are a lot of transactions which are spam. They prevent actual transactions to go through. There are people out there who wait for 14 days for only one transaction. So it is not possible to process the payment until it is verified by the network.

So accept-nano is not directly related to spam attacks. Yes payments will be processed so late but eventually they will. It is much more related to nano nodes and the network.

Hopefully it clarifies things for you!

**Comment by MihaiVoinea** [comment]
Thanks a lot for taking the time to explain!

I have one last question: what would happen in case of a spam attack if a transaction arrives after the AllowedDuration in accept-nano? I would suppose that would require manual admin intervention, because accept-nano wouldn't be checking that address after AllowedDuration expires, right?

Once again, thanks a lot for the explanations!

**Comment by BatuAksoy** [comment]
Yes @MihaiVoinea, you are exactly right. Accept-nano will no longer check payments after `AllowedDuration`. And admins should have to trigger actions themselves in that case.

No worries at all, if you have any other questions, I would be more than happy to help.

**Comment by MihaiVoinea** [comment]
That's all, thanks a lot!

This seems perfect for my needs.

I'll let you know when my project with accept-nano is launched! 😁
